export const WORDS = [
  'Núi lửa', 'Thác nước', 'Sông ngòi', 'Biển cả', 'Sa mạc',
  'Rừng rậm', 'Đồng cỏ', 'Hồ nước', 'Đầm lầy', 'Hang động',
  'Vách đá', 'Bãi biển', 'Đảo san hô', 'Suối nước', 'Cánh đồng',
  'Thung lũng', 'Cao nguyên', 'Đồi cát', 'Sông băng', 'Rạn san hô',
  'Mỏ vàng', 'Hẻm núi', 'Đồng bằng', 'Bán đảo', 'Vịnh biển',
  'Ốc đảo', 'Mũi đất', 'Bờ biển', 'Dãy núi', 'Khe suối',
  'Cửa sông', 'Hòn đảo', 'Thảo nguyên', 'Rừng thông', 'Rừng ngập mặn',
  'Đèo cao', 'Ghềnh đá', 'Hố sâu', 'Đỉnh núi', 'Chân trời',
  'Con hổ', 'Con sư tử', 'Con voi', 'Con rồng', 'Con cá voi',
  'Con đại bàng', 'Chim cánh cụt', 'Con bạch tuộc', 'Con rắn hổ', 'Con cá sấu',
  'Con gấu trúc', 'Con khỉ', 'Con ngựa', 'Con mèo', 'Con chó',
  'Con thỏ', 'Con hươu', 'Con nai', 'Con sóc', 'Con ong',
  'Con bướm', 'Con kiến', 'Con nhện', 'Con ếch', 'Con rùa',
  'Con cua', 'Con tôm', 'Con sứa', 'Cá heo', 'Cá mập',
  'Con công', 'Con gà', 'Con vịt', 'Con ngỗng', 'Con bồ câu',
  'Con quạ', 'Con két', 'Con cú', 'Con diều hâu', 'Con hải cẩu',
  'Con lạc đà', 'Con tê giác', 'Con hà mã', 'Con báo', 'Con sói',
  'Con cáo', 'Con gấu', 'Cá ngựa', 'Con dơi', 'Con bọ cạp',
  'Phở bò', 'Bánh mì', 'Bún chả', 'Gỏi cuốn', 'Chả giò',
  'Bánh xèo', 'Cơm tấm', 'Bún bò Huế', 'Mì Quảng', 'Bánh cuốn',
  'Xôi gấc', 'Chè đậu', 'Kem dừa', 'Nước mía', 'Trà đá',
  'Cà phê sữa', 'Sinh tố', 'Nước dừa', 'Bia hơi', 'Rượu vang',
  'Sầu riêng', 'Xoài chín', 'Thanh long', 'Chôm chôm', 'Măng cụt',
  'Dưa hấu', 'Chuối tiêu', 'Bưởi da xanh', 'Mít tố nữ', 'Vải thiều',
  'Nhãn lồng', 'Ổi xá lị', 'Cam sành', 'Quýt đường', 'Dâu tây',
  'Bánh chưng', 'Nem chua', 'Giò lụa', 'Thịt kho', 'Canh chua',
  'Lẩu nấm', 'Gà nướng', 'Tôm hùm', 'Cá thu', 'Mực nướng',
  'Sushi', 'Pizza', 'Hamburger', 'Chocolate', 'Kẹo cao su',
  'Cái búa', 'Cái kéo', 'Cái dao', 'Cái thìa', 'Cái đũa',
  'Cái nồi', 'Cái chảo', 'Cái ly', 'Cái bát', 'Cái đĩa',
  'Cây nến', 'Cái gương', 'Cái ô', 'Chìa khóa', 'Ổ khóa',
  'Cái quạt', 'Cái ghế', 'Cái bàn', 'Cái giường', 'Cái tủ',
  'Cái chuông', 'Cái còi', 'Sợi dây', 'Cái thang', 'Cái xô',
  'Cái xẻng', 'Cái cuốc', 'Cái rìu', 'Cái cưa', 'Đinh vít',
  'Cái bẫy', 'Cái lồng', 'Cái rổ', 'Cái thúng', 'Cái chổi',
  'Cái mỏ lết', 'Cái kìm', 'Cái đèn pin', 'La bàn', 'Ống nhòm',
  'Bác sĩ', 'Y tá', 'Giáo viên', 'Kỹ sư', 'Kiến trúc sư',
  'Luật sư', 'Phi công', 'Thủy thủ', 'Đầu bếp', 'Thợ mộc',
  'Thợ điện', 'Thợ may', 'Nông dân', 'Ngư dân', 'Thợ săn',
  'Nhà báo', 'Phóng viên', 'Diễn viên', 'Ca sĩ', 'Họa sĩ',
  'Nhạc sĩ', 'Nhà thơ', 'Nhà văn', 'Nhà khoa học', 'Thám tử',
  'Cảnh sát', 'Lính cứu hỏa', 'Phi hành gia', 'Thợ lặn', 'Thợ rèn',
  'Thợ hàn', 'Dược sĩ', 'Nha sĩ', 'Thú y', 'Huấn luyện viên',
  'Trọng tài', 'Thợ cắt tóc', 'Nhiếp ảnh gia', 'Nhà ngoại giao', 'Thợ kim hoàn',
  'Bóng đá', 'Bóng rổ', 'Bóng chuyền', 'Bóng bàn', 'Cầu lông',
  'Quần vợt', 'Bơi lội', 'Điền kinh', 'Đua xe', 'Leo núi',
  'Trượt tuyết', 'Lướt sóng', 'Đấu kiếm', 'Bắn cung', 'Cử tạ',
  'Đấu vật', 'Boxing', 'Judo', 'Karate', 'Taekwondo',
  'Cờ vua', 'Bi-a', 'Bowling', 'Golf', 'Khúc côn cầu',
  'Bóng ném', 'Chạy marathon', 'Nhảy xa', 'Nhảy cao', 'Ném đĩa',
  'Đua thuyền', 'Chèo thuyền', 'Đua ngựa', 'Polo', 'Bóng bầu dục',
  'Xe đạp đua', 'Lặn biển', 'Trượt băng', 'Thể dục dụng cụ', 'Võ thuật',
  'Đàn guitar', 'Đàn piano', 'Trống trận', 'Sáo trúc', 'Đàn tranh',
  'Đàn bầu', 'Đàn nhị', 'Kèn trumpet', 'Violin', 'Đàn harp',
  'Trống đồng', 'Đàn tỳ bà', 'Cồng chiêng', 'Kèn harmonica', 'Accordion',
  'Đàn ukulele', 'Bản nhạc', 'Giai điệu', 'Dàn nhạc', 'Ban nhạc',
  'Micro', 'Loa thùng', 'Đĩa nhạc', 'Sân khấu', 'Phòng thu',
  'Thanh kiếm', 'Tấm khiên', 'Mũi giáo', 'Cung tên', 'Áo giáp',
  'Pháo đài', 'Thành trì', 'Lâu đài', 'Kim tự tháp', 'Vạn Lý',
  'Hoàng đế', 'Nữ hoàng', 'Hiệp sĩ', 'Chiến binh', 'Tướng quân',
  'Samurai', 'Viking', 'Pharaoh', 'Gladiator', 'Chiến xa',
  'Đại bác', 'Xe tăng', 'Chiến hạm', 'Tàu ngầm', 'Mìn bẫy',
  'Lá cờ', 'Vương miện', 'Ngai vàng', 'Con dấu', 'Bản đồ cổ',
  'Kính hiển vi', 'Ống nghiệm', 'Tế bào', 'Phân tử', 'Nguyên tử',
  'Proton', 'Electron', 'Nam châm', 'Pin điện', 'Mạch điện',
  'Robot', 'Máy tính', 'Điện thoại', 'Internet', 'Vệ tinh',
  'Tên lửa', 'Kính thiên văn', 'Thấu kính', 'Nhiệt kế', 'Cân điện tử',
  'Laser', 'Radar', 'Sonar', 'Tia X', 'DNA',
  'Vaccine', 'Virus', 'Vi khuẩn', 'Gen di truyền', 'Hóa thạch',
  'Máy in 3D', 'Chip bán dẫn', 'Máy phát điện', 'Tấm pin mặt trời', 'Cáp quang',
  'Ổ cứng', 'USB', 'Màn hình', 'Bàn phím', 'Con chuột',
  'Xe máy', 'Xe đạp', 'Ô tô', 'Xe buýt', 'Xe lửa',
  'Tàu hỏa', 'Máy bay', 'Trực thăng', 'Tàu thủy', 'Thuyền buồm',
  'Ca nô', 'Xe cứu thương', 'Xe cảnh sát', 'Xe cứu hỏa', 'Xe tải',
  'Xe bồn', 'Xe rác', 'Xe cần cẩu', 'Xe ủi', 'Xe lu',
  'Khinh khí cầu', 'Tàu điện', 'Cáp treo', 'Thang máy', 'Thang cuốn',
  'Xích lô', 'Xe kéo', 'Xuồng máy', 'Phà biển', 'Tàu cao tốc',
  'Áo dài', 'Áo sơ mi', 'Quần jeans', 'Váy đầm', 'Áo khoác',
  'Áo len', 'Áo vest', 'Áo mưa', 'Khăn quàng', 'Mũ bảo hiểm',
  'Mũ nón', 'Giày thể thao', 'Dép tông', 'Ủng cao su', 'Găng tay',
  'Kính râm', 'Đồng hồ đeo tay', 'Dây chuyền', 'Nhẫn cưới', 'Bông tai',
  'Vòng tay', 'Thắt lưng', 'Ví da', 'Ba lô', 'Túi xách',
  'Cà vạt', 'Nơ bướm', 'Mũ phớt', 'Khăn tay', 'Trái tim',
  'Bộ não', 'Lá phổi', 'Dạ dày', 'Xương sống', 'Bàn tay',
  'Bàn chân', 'Ngón tay', 'Khuỷu tay', 'Đầu gối', 'Lông mày',
  'Lưỡi', 'Răng nanh', 'Tai', 'Mũi', 'Cổ tay',
  'Mắt cá chân', 'Gót chân', 'Vai', 'Cằm', 'Trán',
  'Má', 'Cơ bắp', 'Gân', 'Mạch máu', 'Nụ cười',
  'Giọt nước mắt', 'Tiếng cười', 'Tiếng khóc', 'Cái ôm', 'Nụ hôn',
  'Giấc mơ', 'Cơn ác mộng', 'Nỗi nhớ', 'Lời hứa', 'Bí mật',
  'Kỷ niệm', 'Hy vọng', 'Niềm tin', 'Sự dũng cảm', 'Bảng đen',
  'Phấn trắng', 'Cục tẩy', 'Bút chì', 'Bút mực', 'Thước kẻ',
  'Compa', 'Cặp sách', 'Sách giáo khoa', 'Vở bài tập', 'Bản đồ',
  'Quả địa cầu', 'Kính lúp', 'Máy chiếu', 'Bảng trắng', 'Phòng thí nghiệm',
  'Thư viện', 'Sân trường', 'Cổng trường', 'Lớp học', 'Ống tiêm',
  'Viên thuốc', 'Băng gạc', 'Xe lăn', 'Nạng gỗ', 'Khẩu trang',
  'Ống nghe', 'Máy siêu âm', 'Giường bệnh', 'Phòng mổ', 'Áo blouse',
  'Bình oxy', 'Túi máu', 'Ông nội', 'Bà ngoại', 'Bố mẹ',
  'Anh trai', 'Chị gái', 'Em bé', 'Cháu nội', 'Cô dâu',
  'Chú rể', 'Phù dâu', 'Đám cưới', 'Lễ ăn hỏi', 'Bữa cơm',
  'Album ảnh', 'Gia phả', 'Cơn bão', 'Sấm sét', 'Cầu vồng',
  'Bông tuyết', 'Mưa đá', 'Sương mù', 'Lốc xoáy', 'Sóng thần',
  'Động đất', 'Hạn hán', 'Lũ lụt', 'Giông tố', 'Mưa rào',
  'Nắng gắt', 'Gió mùa', 'Sương giá', 'Mây tích', 'Bão cát',
  'Tuyết lở', 'Dòng nham thạch', 'Mặt trời', 'Mặt trăng', 'Ngôi sao',
  'Sao Hỏa', 'Sao Kim', 'Sao Thổ', 'Sao Mộc', 'Dải Ngân Hà',
  'Hố đen', 'Sao chổi', 'Thiên thạch', 'Tinh vân', 'Trạm vũ trụ',
  'Tàu vũ trụ', 'Phi thuyền', 'Nhật thực', 'Nguyệt thực', 'Chòm sao',
  'Mái nhà', 'Cửa sổ', 'Cửa chính', 'Ban công', 'Sân thượng',
  'Tầng hầm', 'Gác xép', 'Cầu thang', 'Hàng rào', 'Cổng sắt',
  'Bồn tắm', 'Vòi sen', 'Bồn cầu', 'Bồn rửa', 'Tủ lạnh',
  'Máy giặt', 'Lò vi sóng', 'Bếp ga', 'Nồi cơm điện', 'Máy hút bụi',
  'Đèn chùm', 'Rèm cửa', 'Thảm trải', 'Gối ôm', 'Chăn bông',
  'Tủ sách', 'Kệ giày', 'Bàn ăn', 'Sofa', 'Tủ quần áo',
  'Con xúc xắc', 'Quân bài', 'Bàn cờ', 'Con rối', 'Bong bóng',
  'Diều giấy', 'Đu quay', 'Tàu lượn', 'Đu dây', 'Vòng xoay',
  'Rạp chiếu phim', 'Rạp xiếc', 'Công viên nước', 'Sở thú', 'Bảo tàng',
  'Rạp hát', 'Sân vận động', 'Phim kinh dị', 'Phim hài', 'Phim hành động',
  'Trò chơi điện tử', 'Máy game', 'Tay cầm', 'Bộ xếp hình', 'Rubik',
  'Bức tranh', 'Bức tượng', 'Bảng màu', 'Cọ vẽ', 'Giá vẽ',
  'Khung tranh', 'Tranh sơn dầu', 'Tranh thủy mặc', 'Tranh lụa', 'Gốm sứ',
  'Thư pháp', 'Điêu khắc', 'Mosaic', 'Graffiti', 'Múa rối nước',
  'Kịch nói', 'Tuồng chèo', 'Opera', 'Ballet', 'Thần Zeus',
  'Thần Thor', 'Phượng hoàng', 'Kỳ lân', 'Nhân mã', 'Người sói',
  'Ma cà rồng', 'Tiên nữ', 'Yêu tinh', 'Quỷ dữ', 'Thần đèn',
  'Thảm bay', 'Gậy thần', 'Bùa hộ mệnh', 'Nàng tiên cá', 'Minotaur',
  'Medusa', 'Người khổng lồ', 'Thần biển', 'Rồng lửa', 'Nhà thờ',
  'Chùa chiền', 'Đền thờ', 'Tháp Eiffel', 'Tháp đồng hồ', 'Cầu treo',
  'Đập thủy điện', 'Ngọn hải đăng', 'Tòa nhà chọc trời', 'Cung điện', 'Vòm đá',
  'Cột trụ', 'Mái vòm', 'Tường thành', 'Cổng thành', 'Tháp chuông',
  'Giếng nước', 'Bến tàu', 'Sân bay', 'Nhà ga', 'Hoa sen',
  'Hoa mai', 'Hoa đào', 'Hoa hồng', 'Hoa cúc', 'Hoa lan',
  'Hoa tulip', 'Hoa hướng dương', 'Hoa phượng', 'Hoa sứ', 'Cây tre',
  'Cây thông', 'Cây sồi', 'Cây dừa', 'Cây bàng', 'Cây xương rồng',
  'Cây nấm', 'Cỏ bốn lá', 'Rong biển', 'Tầm gửi', 'Cây bonsai',
  'Cây liễu', 'Cây phong', 'Dây leo', 'Rễ cây', 'Kim cương',
  'Vàng ròng', 'Bạc nguyên chất', 'Ngọc trai', 'Hổ phách', 'Ngọc bích',
  'Ruby', 'Sapphire', 'Thạch anh', 'Đá cẩm thạch', 'Than đá',
  'Quặng sắt', 'Đá granite', 'Đá vôi', 'Pha lê', 'Bánh tráng',
  'Bắp rang bơ', 'Kẹo dẻo', 'Bánh quy', 'Kem ốc quế', 'Bánh flan',
  'Chè ba màu', 'Trà sữa', 'Bánh bao', 'Bánh dày', 'Kẹo bông',
  'Mứt gừng', 'Hạt dưa', 'Hạt điều', 'Đậu phộng', 'Khẩu súng',
  'Quả bom', 'Lựu đạn', 'Dao găm', 'Mũi tên', 'Nỏ thần',
  'Phi tiêu', 'Gậy bóng chày', 'Boomerang', 'Áo chống đạn', 'Lá chắn',
  'Mũ sắt', 'Dây thép gai', 'Hào chiến đấu', 'Lô cốt', 'Dao thái',
  'Thớt gỗ', 'Máy xay sinh tố', 'Lò nướng', 'Nồi áp suất', 'Máy pha cà phê',
  'Ấm đun nước', 'Hộp đựng cơm', 'Khay đá', 'Khuôn bánh', 'Đũa nấu',
  'Muôi canh', 'Vỉ nướng', 'Nồi lẩu', 'Bình giữ nhiệt', 'Búp bê',
  'Gấu bông', 'Ô tô đồ chơi', 'Đất nặn', 'Bóng bay', 'Máy bay giấy',
  'Lego', 'Bộ domino', 'Con quay', 'Súng nước', 'Kính vạn hoa',
  'Đèn lồng', 'Mặt nạ', 'Máy in', 'Máy photo', 'Máy scan',
  'Ghế xoay', 'Bàn làm việc', 'Kẹp giấy', 'Kim bấm', 'Bìa hồ sơ',
  'Phong bì', 'Con dấu mực', 'Bảng tên', 'Lịch bàn', 'Đồng hồ treo tường',
  'Máy hủy giấy', 'Bút đánh dấu', 'Tivi', 'Radio', 'Báo giấy',
  'Tạp chí', 'Máy ảnh', 'Máy quay phim', 'Loa phóng thanh', 'Ăng ten',
  'Đĩa CD', 'Băng cassette', 'Tượng Phật', 'Cây thánh giá', 'Chuỗi tràng hạt',
  'Bát hương', 'Nén nhang', 'Chuông chùa', 'Lư hương', 'Kinh thánh',
  'Bàn thờ', 'Lá bùa', 'Con sò', 'Vỏ ốc', 'Tảng băng trôi',
  'Đáy biển', 'Cá chép', 'Cá kiếm', 'Sao biển', 'Cầu gai',
  'Đàn đá', 'Đàn nguyệt', 'Khèn mông', 'Trống cơm', 'Phách tre',
  'Mõ gỗ', 'Sáo bầu', 'Kèn bầu', 'Đàn tam', 'Mắm tôm',
  'Nước mắm', 'Tương ớt', 'Mù tạt', 'Tiêu đen', 'Quế hồi',
  'Gừng tươi', 'Tỏi tây', 'Hành tím', 'Ớt hiểm', 'Đường phèn',
  'Muối hột', 'Dấm gạo', 'Bơ thực vật', 'Mật ong', 'Lọ hoa',
  'Khung ảnh', 'Đồng hồ cát', 'Quả cầu tuyết', 'Chuông gió', 'Đèn lava',
  'Bình gốm', 'Tranh treo tường', 'Siêu nhân', 'Người nhện', 'Người dơi',
  'Ninja', 'Cướp biển', 'Cao bồi', 'Thám tử tư', 'Phù thủy',
  'Pháp sư', 'Thiên thần', 'Hồ Gươm', 'Phố cổ Hội An', 'Vịnh Hạ Long',
  'Sapa', 'Đà Lạt', 'Phú Quốc', 'Côn Đảo', 'Fansipan',
  'Tháp Pisa', 'Angkor Wat', 'Taj Mahal', 'Colosseum', 'Stonehenge',
  'Machu Picchu', 'Tử Cấm Thành', 'Tết Nguyên Đán', 'Trung Thu', 'Lễ Giáng Sinh',
  'Halloween', 'Lễ hội hoa', 'Đua thuyền rồng', 'Carnival', 'Pháo hoa',
  'Diễu hành', 'Đồng tiền', 'Thỏi vàng', 'Két sắt', 'Ngân hàng',
  'Máy ATM', 'Thẻ tín dụng', 'Heo đất', 'Túi tiền', 'Xâu tiền xu',
  'Truyện tranh', 'Sách cổ', 'Bản thảo', 'Cuộn giấy', 'Bút lông',
  'Mực tàu', 'Giấy da', 'Hình tròn', 'Tam giác', 'Hình vuông',
  'Hình lục giác', 'Hình cầu', 'Hình trụ', 'Hình nón', 'Xoắn ốc',
  'Đường thẳng', 'Bún đậu', 'Xúc xích', 'Bánh tráng trộn', 'Ngô nướng',
  'Khoai lang nướng', 'Ốc luộc', 'Hột vịt lộn', 'Cháo lòng', 'Hủ tiếu',
  'Bánh canh', 'Con chuồn chuồn', 'Con bọ rùa', 'Con đom đóm', 'Con giun đất',
  'Con ốc sên', 'Con châu chấu', 'Con dế mèn', 'Con bọ ngựa', 'Con ve sầu',
  'Con muỗi', 'Bàn DJ', 'Ampli', 'Tai nghe', 'Máy đánh nhịp',
  'Pedal guitar', 'Máy tính bảng', 'Đồng hồ thông minh', 'Máy chơi game', 'Drone',
  'Loa bluetooth', 'Sạc dự phòng', 'Kính thực tế ảo', 'Camera an ninh', 'Bộ phát wifi',
  'Bột mì', 'Gạo nếp', 'Đậu xanh', 'Đậu đỏ', 'Đậu nành',
  'Bắp ngô', 'Khoai tây', 'Cà rốt', 'Bí đỏ', 'Rau muống',
  'Cải thảo', 'Hành lá', 'Rau mùi', 'Sả cây', 'Lá chanh',
  'Mỏ neo', 'Cánh buồm', 'Bánh lái', 'Phao cứu sinh', 'Hải đồ',
  'Cột buồm', 'Boong tàu', 'Khoang hàng', 'Thủy triều', 'Hải lưu',
  'Cái cày', 'Máy gặt', 'Máy cày', 'Bó lúa', 'Cối xay',
  'Kho thóc', 'Ruộng bậc thang', 'Nhà kính', 'Áo da', 'Mũ cao bồi',
  'Guốc mộc', 'Yếm đào', 'Nón lá', 'Khăn rằn', 'Áo bà ba',
  'Đai lưng', 'Khăn choàng cổ', 'Phô mai', 'Giăm bông', 'Đồ hộp',
  'Mì gói', 'Ngũ cốc', 'Sữa chua', 'Đậu hũ', 'Chả cá',
  'Viên gạch', 'Tấm kính', 'Thanh sắt', 'Bao xi măng', 'Tấm gỗ',
  'Viên ngói', 'Sợi thép', 'Ống nước', 'Dây điện', 'Tấm tôn',
  'Toán học', 'Vật lý', 'Hóa học', 'Sinh học', 'Lịch sử',
  'Địa lý', 'Văn học', 'Triết học', 'Thiên văn học', 'Tâm lý học',
  'Trà xanh', 'Nước ép cam', 'Sữa đậu nành', 'Nước khoáng', 'Cacao nóng',
  'Bắc Cực', 'Nam Cực', 'Xích đạo', 'Kinh tuyến', 'Vĩ tuyến',
  'Cá cảnh', 'Chim cảnh', 'Hamster', 'Rùa cảnh', 'Mâm ngũ quả',
  'Bánh trung thu', 'Cây nêu', 'Câu đối', 'Lì xì', 'Tầng ozone',
  'Khí quyển'
];
